import React from 'react';
const Descripcion = () => {
    return ( 
        <div data-purpose="safely-set-inner-html:description:description">
  <p>Aprende el lenguaje más popular! JavaScript!</p>
  <p>El curso incluye<strong> ES6, ES7, ES8, ES9 y ES10</strong>
  </p><p>También el curso incluye webpack, node.js, express, mongodb, react, electron y mucho más!</p><p>En este curso aprenderás JavaScript desde los fundamentos hasta temas más avanzados como <strong>Prototypes, Delegation, Classes, Ajax, Promises, Generadores,&nbsp;Orientado a Objetos, Fetch API, Async Await, Async JS, Objetos,&nbsp;así como consumir REST APIs</strong> entre muchos más.</p><p>Si estos temas no son de tu conocimiento, estas en el curso adecuado para aprenderlos!</p><p><strong>La mejor forma de aprender es desarrollando algo, en este curso crearemos bastantes proyectos que te llevaran desde el nivel básico hasta avanzado!</strong></p><p><strong>Los Proyectos desarrollados incluyen:</strong></p><ul><li><p>Formulario para guardar a Local Storage</p></li><li><p>Cotizador de Seguros de Auto</p></li><li><p>Simulador de Envio de Emails</p></li><li><p>Generador de Nombres desde una REST API</p></li><li><p>Cotizador de Criptomonedas desde una REST API ( Más de 100 incluidas)</p></li><li><p>Eventos en tu ciudad con Event Brite y REST API</p></li><li><p>Carrito de Compras con Local Storage</p></li><li><p>Gasto Semanal&nbsp;</p></li><li><p>Agenda de Pacientes de Veterinaria</p></li><li><p>Buscador de Letras de Canciones</p></li><li><p>Mostrar Establecimientos con Mapas (Leaflet) desde una API Externa</p></li><li><p>Buscador y Filtro de Automoviles con Higher Order Functions</p></li><li><p> Cotizador de Prestamos con Intereses a pagar <strong>(Desarrollado en React)</strong></p></li><li><p>Sitio web para una Agencia de Viajes<strong> (Desarrollado con NodeJS y Sequelize)</strong></p></li><li><p>FullStack JavaScript con <strong>React, Express, MongoDB, Node y Electron</strong></p></li></ul><p>Todos los proyectos utilizan técnicas distintas, por lo cual te servirán para conocer distintas formas de realizar estos proyectos.</p><p><strong>LOS PROYECTOS ESTÁN HABILITADOS PARA VERSE DE FORMA GRATUITA</strong></p><p>JavaScript es el lenguaje más popular para web hoy en día, y puede utilizarse en el cliente o Servidor, en este curso aprenderás todo lo necesario y es una excelente introducción si quieres aprender librerías nuevas como VueJS, React, Angular o NodeJS
  </p><p><br /></p></div>

    );
}
 
export default Descripcion;